services:
- type: web
  name: rastreo-backend
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn backend_app.wsgi:application
  envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: backend_app.settings